In [36]:
import numpy as np

1. Задати вектор, що складається з перших п'яти натуральних чисел.

In [37]:
vector = np.array([1,2,3,4,5])
vector


array([1, 2, 3, 4, 5])

2. Транспортувати вектор

In [38]:
v1 = np.matrix([1,2,3,4,5])
print(v1)
v2 = v1.T
v2

[[1 2 3 4 5]]


matrix([[1],
        [2],
        [3],
        [4],
        [5]])

3. Напишіть функцію, яка перевертає вектор у зворотньому порядку

In [39]:
v = np.array([1,2,3,4,5])
print(v[::-1])

[5 4 3 2 1]


In [40]:
v = np.flip(v)
print(v)

[5 4 3 2 1]


4. Обчислити середнє значення вектора

In [41]:
print(np.mean(v))

3.0


5. Знайти найбільший і найменший елементи вектора

In [42]:
print(np.max(v))
print(np.min(v))

5
1


6. Обчислити скалярний добуток (dot product) двох векторів

In [43]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

print(np.dot(v1,v2))
print(v1*v2)

32
[ 4 10 18]


7. Напишіть функцію яка нормалізує вектор (зводить до одиничної довжини).

In [44]:
v = np.array([1,2,3,4,5])
norm = np.linalg.norm(v)

print(norm)

v/norm

7.416198487095663


array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986])

8. Задайте два вектори. Визначте, чи є вони ортогональними. Підказка: якщо скалярний добуток дорівнює нулю - вектори ортогональні.

In [45]:
v1 = np.array([1,0,0])
v2 = np.array([0,1,0])

np.dot(v1,v2)

np.int64(0)

9. Визначити унікальні елементи вектора

In [46]:
v = np.array([1,2,3,2,4,5,3])
np.unique(v)

array([1, 2, 3, 4, 5])

10. Знайти вектори

In [47]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

print(v1 - v2)
print(v2 - v1)
print(v1 + v2)
print(v2 + v1)
print(v1 * v2)
print(v2 * v1)
print(v1 / v2)
print(v2 / v1)

[-3 -3 -3]
[3 3 3]
[5 7 9]
[5 7 9]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4.  2.5 2. ]


11. Перевірити, чи дорівнює довжина вектора 5

In [48]:
vector = np.array([1,2,3,4,5])
length = np.linalg.norm(vector)

np.isclose(length, 5)

np.False_

12. Задати матрицю, заповнену випадковими числами

In [49]:
a = np.random.randint(0,11,(3,3))
a

array([[ 9,  0,  7],
       [10,  2,  4],
       [ 3,  2,  1]])

13. Обчислити визначник матриці

In [50]:
np.linalg.det(a)

np.float64(44.000000000000014)

14. Знаходження оберненої матриці

In [51]:
np.linalg.inv(a)

array([[-0.13636364,  0.31818182, -0.31818182],
       [ 0.04545455, -0.27272727,  0.77272727],
       [ 0.31818182, -0.40909091,  0.40909091]])

15. Розв'яжіть систему лінійних рівнянь A*x=b, де A - матриця коефіцієнтів, b - вектор вільних членів.

In [52]:
a = np.array([[1,3,-4], [0,2,-3], [-2,2,5]])
b = np.array([5,3,4])

x = np.linalg.solve(a,b)
print(x)

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print(x1)

[0.38888889 1.83333333 0.22222222]
[0.38888889 1.83333333 0.22222222]


16. Множення двох матриць

In [53]:
a = np.array([[1,3,-4], [0,2,-3], [-2,2,5]])
b = np.array([5,3,4])

np.dot(a,b)

array([-2, -6, 16])

In [54]:
a = np.matrix([[1,3,-4], [0,2,-3]])
b = np.matrix([[5,3,4], [2,3,5], [3,2,3]])
print(a)
print(b)
print(np.dot(a,b))

[[ 1  3 -4]
 [ 0  2 -3]]
[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[-1  4  7]
 [-5  0  1]]


17. Транспонування матриці

In [55]:
print(a.T)
print(b.T)

[[ 1  0]
 [ 3  2]
 [-4 -3]]
[[5 2 3]
 [3 3 2]
 [4 5 3]]


In [56]:
print(np.transpose(a))
print(np.transpose(b))

[[ 1  0]
 [ 3  2]
 [-4 -3]]
[[5 2 3]
 [3 3 2]
 [4 5 3]]


18. Перевірка симетричності матриці

In [57]:
matrix = np.matrix([[2,2,2], [2,2,2], [2,2,2]])

np.allclose(matrix, matrix.T)

True

19. Обчислення сліду матриці

In [58]:
np.trace(matrix)

np.int64(6)

20. Дії з матрицями

In [59]:
a = np.matrix([[1,2], [3,4]])
b = np.matrix([[5,6], [7,8]])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


21. Піднесення матриці до ступеня

In [60]:
a = np.matrix([[1,2], [3,4]])

np.linalg.matrix_power(a,2)

matrix([[ 7, 10],
        [15, 22]])

22. Сортування рядків або стовпців матриці

In [61]:
b = np.matrix([[5,3,4], [2,3,5], [3,2,3]])

print(b)
print(np.sort(b, axis=0))
print(np.sort(b, axis=1))
print(np.sort(b, axis= None))

[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[2 2 3]
 [3 3 4]
 [5 3 5]]
[[3 4 5]
 [2 3 5]
 [2 3 3]]
[[2 2 3 3 3 3 4 5 5]]


In [62]:
a = np.array([[1,4], [3,1]])

print(a)
print(np.sort(a))

[[1 4]
 [3 1]]
[[1 4]
 [1 3]]


23. Підрахувати суму елементів кожного рядка матриці. Відповідь запиши, як вектор стовпчик.

In [63]:
row_sums = np.sum(a, axis=1).reshape(-1,1)

print("Сума елементів кожного рядка:")
print(row_sums)
# В результаті отримали вектор - стовпчик

Сума елементів кожного рядка:
[[5]
 [4]]


**Висновок:** робота закріпила навички роботи з масивами, векторами та матрицями в Python, а також застосування базових лінійних та статистичних операцій.