In [ ]:
import numpy as np
np.__version__

'2.0.2'

1. Створи матрицю 3*3, заповни її цілими випадковими числами від 1 до 5.

In [ ]:
matrix = np.random.randint(1, 6, size=(3, 3))

matrix

array([[3, 3, 3],
       [2, 2, 4],
       [2, 4, 5]])

2. Обчислити визначник матриці.

In [ ]:
det = np.linalg.det(matrix)
det

np.float64(-12.0)

3. Знайти добуток всіх елементів матриці.

In [ ]:
product = np.prod(matrix)
product

np.int64(17280)

In [ ]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(17280)

4. Знайти суму всіх елементів матриці.

In [ ]:
sum = np.sum(matrix)

sum

np.int64(28)

5. Обчислити найбільший та найменший елементи.

In [ ]:
max_element = np.max(matrix)

print("Найбільший елемент матриці:", max_element)

min_element = np.min(matrix)

print("Найменший елемент матриці:", min_element)

Найбільший елемент матриці: 5
Найменший елемент матриці: 2


6. Знайти середнє значення елементів матриці.

In [ ]:
mean = np.mean(matrix)

print("Середнє значення елементів матриці:", mean)

Середнє значення елементів матриці: 3.111111111111111


7. Знайти матрицю, що складена з квадратних коренів.

In [ ]:
sqrt_matrix = np.sqrt(matrix)

print("Матриця квадратних коренів:")
print(sqrt_matrix)

Матриця квадратних коренів:
[[1.73205081 1.73205081 1.73205081]
 [1.41421356 1.41421356 2.        ]
 [1.41421356 2.         2.23606798]]


8. Обчислити суму елементів кожного рядка. Відповідь записати як вектор-стовпчик.

In [ ]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)

print("Сума елементів кожного рядка:")
print(row_sums)
#В результаті отримали вектор - стовпчик.

Сума елементів кожного рядка:
[[ 9]
 [ 8]
 [11]]


9. Створити вектор, що містить 25 елементів. Заповинити числамии від 0 до 9. Відсортувати числа за спаданням.

In [ ]:
vector = np.random.randint(0, 10, size=25)

print("Початковий вектор:")
print(vector)

#Сортуємо числа за спаданням
sorted_vector = np.sort(vector)[::-1]

print("Вектор після сортування за спаданням:")
print(sorted_vector)

Початковий вектор:
[9 2 0 5 4 3 4 7 9 5 6 3 0 5 6 0 2 1 3 5 4 5 9 4 7]
Вектор після сортування за спаданням:
[9 9 9 7 7 6 6 5 5 5 5 5 4 4 4 4 3 3 3 2 2 1 0 0 0]


10. Знайти моду, медіану, середнє, максимальне, мінімальне значення.

In [ ]:
from scipy import stats
#Знаходимо моду
mode = stats.mode(vector)

#Знаходимо медіану
median = np.median(vector)

#Знаходимо середнє
mean = np.mean(vector)

#Знаходимо максимальне значення
max_value = np.max(vector)

#Знаходимо мінімальне значення
min_value = np.min(vector)

print("Мода:", mode)
print("Медіана:", median)
print("Середнє:", mean)
print("Максимальне значення:", max_value)
print("Мінімальне значення:", min_value)

Мода: ModeResult(mode=np.int64(5), count=np.int64(5))
Медіана: 4.0
Середнє: 4.32
Максимальне значення: 9
Мінімальне значення: 0


11. Створити дві матриці 4*4, заповнені числами від 1 до 10. Обчислити суму, різницю, поелементний добуток, частку.

In [ ]:
#Створюємо дві матриці 4х4 із випадкових цілих чисел від 1 до 10.
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

Матриця 1:
[[ 1  6  1  6]
 [ 9  4  1  5]
 [10  6  9  5]
 [10  9  9  4]]

Матриця 2:
[[ 2  9  6  4]
 [ 7  9  2  2]
 [ 1 10  7  5]
 [ 9  2  8  2]]


In [ ]:
#Обчислюємо суму матриць
matrix_sum = matrix1 + matrix2

#Обчислюємо різницю матриць
matrix_diff = matrix1 - matrix2

#Обчислюємо поелементний добуток матриць
matrix_product = matrix1 * matrix2

#Обчислюємо поелементну частку матриць
#Для запобігання ділення на нуль, використовуємо np.divide з параметром where
matrix_division = np.divide(matrix1, matrix2, where=(matrix2!=0))

print("\nСума матриць:")
print(matrix_sum)

print("\nРізниця матриць:")
print(matrix_diff)

print("\nПоелементний добуток матриць:")
print(matrix_product)

print("\nПоелементна частка матриць:")
print(matrix_division)


Сума матриць:
[[ 3 15  7 10]
 [16 13  3  7]
 [11 16 16 10]
 [19 11 17  6]]

Різниця матриць:
[[-1 -3 -5  2]
 [ 2 -5 -1  3]
 [ 9 -4  2  0]
 [ 1  7  1  2]]

Поелементний добуток матриць:
[[ 2 54  6 24]
 [63 36  2 10]
 [10 60 63 25]
 [90 18 72  8]]

Поелементна частка матриць:
[[ 0.5         0.66666667  0.16666667  1.5       ]
 [ 1.28571429  0.44444444  0.5         2.5       ]
 [10.          0.6         1.28571429  1.        ]
 [ 1.11111111  4.5         1.125       2.        ]]
